djangoproject/mysite/ecom/urls.py
from django.urls import path
from ecom.views import index,details,cart_view,checkout,return_view,cancel_view

app_name='ecom'

urlpatterns = [
    path('',index,name='index'),
    path('<int:product_id>/<slug:slug>/',details,name = 'details'),
    path('cart/',cart_view, name = 'cart_view'),
    path('checkout/',checkout, name = 'checkout'),
    path('success/',return_view, name = 'return_view'),
    path('cancel/',cancel_view, name = 'cancel_view'),
]

djangoproject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecom.urls')),
    path('accounts/',include('registration.backends.default.urls')),
    path('paypal/',include('paypal.standard.ipn.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoproject/mysite/ecom/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField()
    slug=models.SlugField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    img=models.ImageField(upload_to = '')
    
    def __str__(self):
        return self.title

class Cart(models.Model):
    cart_id=models.CharField(max_length=50)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    quantity=models.IntegerField()
    timestamp=models.DateTimeField(auto_now=True)
    product=models.ForeignKey(Product,on_delete=models.PROTECT)

    def __str__(self):
        return self.product.title
    def update_quantity(self,quantity):
        self.quantity+=quantity
        self.save()
    def total(self):
        return self.quantity*self.price
class Buy(models.Model):
    product=models.ForeignKey(Product,on_delete=models.PROTECT)
    quantity=models.IntegerField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    
    def __str__(self):
        return self.product.title+'_'+self.id
    
    
    

djangoproject/mysite/ecom/forms.py
from django import forms

class CartForm(forms.Form):
    quantity=forms.IntegerField(initial= '1')
    product_id=forms.IntegerField(widget = forms.HiddenInput)

    def __init__(self,request,*args,**kwargs):
        self.request=request
        super(CartForm,self).__init__(*args,**kwargs)

djangoproject/mysite/ecom/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from ecom.models import Product,Buy
from ecom.forms import CartForm
from ecom.myapp import *
from django.urls import reverse
from django.shortcuts import render
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.backends import *
from django.contrib.auth.decorators import login_required
import uuid
# Create your views here.

def index(request):
    p=Product.objects.all()
    if request.GET.get('q'):
        query = request.GET.get('q')
        p = Product.objects.filter(title__contains = query)
    context={'p':p}
    return render(request,'index.html',context)

@login_required
def details(request,product_id,slug):
    d= Product.objects.get(id = product_id)

    if request.method == 'POST':
        f = CartForm(request,request.POST)
        if f.is_valid(): 
            request.form_data = f.cleaned_data
            add_to_cart(request)
            return redirect('ecom:cart_view')

    f=CartForm(request,initial={'product_id':product_id})
    context={'d':d,'f':f}
    return render(request,'details.html',context)

def cart_view(request):
    if request.method == 'POST' and request.POST.get('delete') == 'Delete': 
        item_id = request.POST.get('item_id')
        cd=Cart.objects.get(id = item_id)
        cd.delete()
    c = get_cart(request)
    t = total_(request)
    co = item_count(request)
    context = {'c':c ,'t':t }
    return render(request,'cart.html',context)

def checkout(request):
    return render(request,'checkout.html')

def checkout(request):
    items = get_cart(request)
    for i in items:
        b=Buy(product_id=i.product_id,quantity=i.quantity,price=i.price)
        b.save()
    # What you want the button to do.
    paypal_dict = {
        "business":"sb-yokpc25418629@business.example.com",
        "amount":total_(request),
        "item_name":cart_id_(request),
        "invoice":str(uuid.uuid4()),
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return_url": request.build_absolute_uri(reverse('ecom:return_view')),
        "cancel_return": request.build_absolute_uri(reverse('ecom:cancel_view')),
        "custom": "premium_plan",
    }
    # Create the instance.
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form":form,"items":items,"total":total_(request)}
    return render(request, 'checkout.html', context)

def return_view(request):
    return HttpResponse('Transaction Successful')

def cancel_view(request):
    return HttpResponse('Transaction Cancelled')

djangoproject/mysite/ecom/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<title></title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">E-Commerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'ecom:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" name="q" value="{{request.GET.q}}" placeholder="Search" aria-label="Search">
          </form>
          <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'ecom:cart_view' %}">Cart({{count}})</a>
          &nbsp;&nbsp;
            {% if not user.is_authenticated %}
            <a class="btn btn-outline-primary" href="{% url 'auth_login' %}">Login</a>&nbsp;
            <a class="btn btn-outline-primary" href="{% url 'registration_register' %}">Register</a>
            {% else %}
            <a class="btn btn-outline-success" href="{% url 'auth_logout' %}">Logout</a>
            {% endif %}
            
        </div>
      </nav>
      <div class="container">
        <br><br>
        {%block content%}
        <!-- Content here -->

        {% endblock %}
      </div>
      <hr class="featurette-divider">
      <footer class="container">
      <p class="float-right"><a href="#">Back to top</a></p>
      <p>&copy; 2023 Company, Inc. &middot; <a href="#">Privacy</a>&middot;<a href="#">Terms</a></p> 
      </footer>
</body>
</html>

djangoproject/mysite/ecom/templates/cart.html
{% extends 'base.html' %}
{% block content %}
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total Cost</th>
      </tr>
    </thead>
    <tbody>
      {% for i in c %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{i.product}}</td>
        <td> ₹{{i.price}}</td>
        <td>{{i.quantity}}</td>
        <td>{{i.total}}</td>
        <td>
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="item_id" value="{{i.id}}">
          <input class="btn btn-danger" type="submit" name="delete" value="Delete">
        </form>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <br><br>
  Total: ₹{{t}}<br>
  <a class="btn btn-secondary" href="{% url 'ecom:checkout' %}">Checkout</a>
  &nbsp;&nbsp;&nbsp;
  <a class="btn btn-secondary" href="{% url 'ecom:index' %}">Back/Continue</a>

{% endblock %}

djangoproject/mysite/ecom/templates/checkout.html
{% extends 'base.html' %}
{% block content %}
<b>Cart:<b><br>
{% for i in items%}
{{i.product}} - {{i.quantity}} - {{i.price}}<br>
{% endfor %}
<br>
Pay : {{Total}}
<br><br>
<h6>Show me the money!</h6>
<!-- writes out the form tag automatically -->
{{ form.render }}
{% endblock %}

djangoproject/mysite/ecom/templates/details.html
{% extends 'base.html' %}
{% block content %}
        <!-- Content here -->
        <div class="row">
        <div class="col-md-6">
                <b>{{d.title}}</b><br>
                {{d.description}}<br>
                <b>₹{{d.price}}</b><br>
        </div>
        <div class="col-md-6">
            <img src="{{d.img.url}}" width="400" height="400">
        </div>
    
        <form action="{% url 'ecom:details' d.id d.slug %}" method="post">
            {% csrf_token %}
            {{ f }}
            <input class="btn btn-primary" type="submit" value="Add to Cart">
        </form>
{% endblock %}

djangoproject/mysite/ecom/templates/index.html
{%extends 'base.html'%}
{%block content%}
        <!-- Content here -->
        <div class="row">
                {% for i in p %}
                <div class="col-md-4">
                <a class="btn btn-outline-info btn-block" href="{% url 'ecom:details' i.id i.slug %}">{{i.title}}</a>
                <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img class="border rounded-pill" src="{{i.img.url}}" width="300px" height="300px"><br>
                ₹{{i.price}}
                <br><br>
        </div>
                {% endfor %}
{%endblock%}